swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /checkings:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get all checking details
      description: API for getting all checking details for user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User retrieved all checking details successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /savings:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get all saving details
      description: API for getting all saving details for user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User retrieved all saving details successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /cards:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get all credit card savings
      description: API for getting all credit card details for user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User retrieved all credit card saving details successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /card/update:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update card detail
      description: API for updating card detail
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update card detail informations
          required: true
          schema:
            $ref: '#/definitions/CardUpdateModel'
          
      produces:
        - application/json
      responses:
        '200':
          description: User card detail updated successfully
          schema:
            $ref: '#/definitions/CardUpdateResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Card detail not found.
        '500':
          description: Internal Server Error
  /saving/update:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update saving detail
      description: API for updating saving detail
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update saving detail informations
          required: true
          schema:
            $ref: '#/definitions/CardUpdateModel'
          
      produces:
        - application/json
      responses:
        '200':
          description: User saving detail updated successfully
          schema:
            $ref: '#/definitions/CardUpdateResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Saving detail not found.
        '500':
          description: Internal Server Error
  /checking/update:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update checking detail
      description: API for updating checking detail
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update checking detail informations
          required: true
          schema:
            $ref: '#/definitions/CardUpdateModel'
          
      produces:
        - application/json
      responses:
        '200':
          description: User checking detail updated successfully
          schema:
            $ref: '#/definitions/CardUpdateResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Checking not found.
        '500':
          description: Internal Server Error
  /checking/{id}:
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete checking by id
      description: API for deleting by id
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: deleting checking detail informations
          required: true
          schema:
            $ref: '#/definitions/CheckingDeleteModel'
          
      produces:
        - application/json
      responses:
        '200':
          description: User checking detail deleting successfully
          schema:
            $ref: '#/definitions/CheckingDeleteResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Checking detail not found.
        '500':
          description: Internal Server Error
  /saving/{id}:
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete saving by id
      description: API for saving by id
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: deleting saving detail informations
          required: true
          schema:
            $ref: '#/definitions/CheckingDeleteModel'
          
      produces:
        - application/json
      responses:
        '200':
          description: User saving detail deleting successfully
          schema:
            $ref: '#/definitions/CheckingDeleteResponse'
        '400':
          description: Invalid Fields
        '404':
          description: saving detail not found.
        '500':
          description: Internal Server Error
  /card/{id}:
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete card detail by id
      description: API for card detail by id
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: deleting card detail informations
          required: true
          schema:
            $ref: '#/definitions/CheckingDeleteModel'
          
      produces:
        - application/json
      responses:
        '200':
          description: User card detail deleting successfully
          schema:
            $ref: '#/definitions/CheckingDeleteResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Card detail not found.
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
      user:
        type: object
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  TransactionModel:
    type: object
    properties:
      id:
        type: integer
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
  CardUpdateModel:
    type: object
    properties:
      transactionId:
        type: integer
      category:
        type: string
      note:
        type: string
  CardUpdateResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      details:
        type: object    
  CheckingDeleteModel:
    type: object
    properties:
      transactionId:
        type: integer
  CheckingDeleteResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
